
# travis phases and our setup
# before_install
# install                           -- fetch/build non-haskell dependencies: savilerow, minion, lingeling
#                                   -- build conjure
#                                   -- save all these executables under $(pwd)/bin
# before_script
# script                            -- running tests
# after_success                     -- attempt cabal freeze
# after_failure
# OPTIONAL before_deploy
# OPTIONAL deploy
# OPTIONAL after_deploy
# after_script

language: c

sudo: false

# superset of all addons
# addons: {apt: {sources: [hvr-ghc, ubuntu-toolchain-r-test], packages: [gcc-4.9, g++-4.9, cabal-install-1.24, ghc-7.8.4, ghc-7.10.3, ghc-8.0.1, ghc-head]}}

# apparently explicitly setting the compiler here forces travis to
# use separate caches for different compiler versions.
# as seen in the Idris .travis.yml
# (until https://github.com/travis-ci/travis-ci/issues/4393 is resolved)
matrix:

  include:

    - os: linux
      env: GHC=7.8.4 SR="-O2" SOL=minion
      compiler: ": # GHC 7.8.4"
      addons: {apt: {sources: [hvr-ghc, ubuntu-toolchain-r-test], packages: [g++-4.9, cabal-install-1.24, ghc-7.8.4]}}

    - os: linux
      env: GHC=7.10.3 SR="-O2" SOL=minion
      compiler: ": # GHC 7.10.3"
      addons: {apt: {sources: [hvr-ghc, ubuntu-toolchain-r-test], packages: [g++-4.9, cabal-install-1.24, ghc-7.10.3]}}

    - os: linux
      env: GHC=8.0.1 SR="-O0" SOL=minion
      compiler: ": # GHC 8.0.1"
      addons: {apt: {sources: [hvr-ghc, ubuntu-toolchain-r-test], packages: [g++-4.9, cabal-install-1.24, ghc-8.0.1]}}
    - os: linux
      env: GHC=8.0.1 SR="-O2" SOL=minion
      compiler: ": # GHC 8.0.1"
      addons: {apt: {sources: [hvr-ghc, ubuntu-toolchain-r-test], packages: [g++-4.9, cabal-install-1.24, ghc-8.0.1]}}
    - os: linux
      env: GHC=8.0.1 SR="-O0" SOL=lingeling
      compiler: ": # GHC 8.0.1"
      addons: {apt: {sources: [hvr-ghc, ubuntu-toolchain-r-test], packages: [gcc-4.9, g++-4.9, cabal-install-1.24, ghc-8.0.1]}}
    - os: linux
      env: GHC=8.0.1 SR="-O2" SOL=lingeling
      compiler: ": # GHC 8.0.1"
      addons: {apt: {sources: [hvr-ghc, ubuntu-toolchain-r-test], packages: [gcc-4.9, g++-4.9, cabal-install-1.24, ghc-8.0.1]}}

    - os: osx
      env: GHC=8.0.1 SR="-O2" SOL=minion
      compiler: ": # GHC 8.0.1"

    - os: linux
      env: GHC=head SR="-O2" SOL=minion
      compiler: ": # GHC head"
      addons: {apt: {sources: [hvr-ghc, ubuntu-toolchain-r-test], packages: [g++-4.9, cabal-install-1.24, ghc-head]}}

  allow_failures:
    - env: GHC=head SR="-O2" SOL=minion
    - os: osx
      env: GHC=8.0.1 SR="-O2" SOL=minion

before_install:
  # expanding the names of the environment variables
  # they were only shorter in the matrix to keep travis ui clean
  - export GHC_VERSION="${GHC}"
  - export SR_OPTIONS="${SR}"
  - export SOLVER="${SOL}"
  #
  - export CABALVER=1.24
  - export BIN_DIR=$(pwd)/bin
  - export PATH=${BIN_DIR}:/opt/ghc/${GHC_VERSION}/bin:/opt/cabal/${CABALVER}/bin:${HOME}/.cabal/bin:${PATH}
  - if [ ${SOLVER} = "minion" ] ; then export SR_OPTIONS="${SR_OPTIONS} -minion" ; fi
  - if [ ${SOLVER} = "lingeling" ] ; then export SR_OPTIONS="${SR_OPTIONS} -sat" ; fi

install:
  - mkdir -p bin

  # Conjure
  - cabal --version || echo "cabal not found"
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - echo ${PATH}
  - OPTIMISATION=-O1 BUILD_TESTS=yes CORES=2 make install-with-cabal
  - conjure --version                        # print version

  # Savile Row
  - (savilerow | grep 'c9d0b46c82b2') || etc/build/install-savilerow.sh
  - savilerow | head -n2 | tail -n1          # print version

  # Lingeling
  - (lingeling --help > /dev/null) || (CC="gcc-4.9" etc/build/install-lingeling.sh)

  # Minion
  # - (minion | grep 'Minion Version 2') || (COMPILER="g++-4.9" etc/build/install-minion.sh)
  - (minion | grep 'Minion Version 1.8') || (etc/build/download-minion.sh)
  - minion help | head -n2                   # print version

  - ls -Alh $(find bin -type f)

script:
  - touch conjure-testing.stdout
  - if ! (find bin -mmin -5 | grep minion); then ((time dist/build/conjure-testing/conjure-testing --select-tests quick +RTS -s) > >(tee conjure-testing.stdout | grep -B1 'Conjuring\|Savile') 2> >(tee conjure-testing.stderr >&2)) || true; fi
  - if ! grep -B10 FAIL conjure-testing.stdout; then echo "Success!"; else exit 1 ; fi
  - cabal sdist   # tests that a source-distribution can be generated

after_success:
  - make freeze

cache:
  directories:
    - ${HOME}/.cabal
    - ${HOME}/.ghc
    - .cabal-sandbox
    - dist
    - bin

