
# travis phases and our setup
# before_install
# install                           -- fetch/build non-haskell dependencies: savilerow, minion, lingeling
#                                   -- build conjure
#                                   -- save all these executables under $(pwd)/bin
# before_script
# script                            -- running tests
# after_success                     -- attempt cabal freeze
# after_failure
# OPTIONAL before_deploy
# OPTIONAL deploy
# OPTIONAL after_deploy
# after_script

language: c

sudo: false

matrix:
  include:
    - env: GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.24, ghc-7.8.4], sources: [hvr-ghc]}}
      compiler: GHC-7.8.4 # apparently this forces travis to use separate caches for different compiler versions
                          # as seen in the Idris .travis.yml
                          # (until https://github.com/travis-ci/travis-ci/issues/4393 is resolved)
    - env: GHCVER=7.10.3
      addons: {apt: {packages: [cabal-install-1.24, ghc-7.10.3], sources: [hvr-ghc]}}
      compiler: GHC-7.10.3

before_install:
 - export CABALVER=1.24
 - export PATH=$(pwd)/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.cabal/bin:$PATH

install:
 - mkdir -p bin

 # Savile Row
 - BIN_DIR=$(pwd)/bin etc/build/install-savilerow.sh

 # Conjure
 - cabal --version || echo "cabal not found"
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - if [ GHCVER=7.8.4 ]; then rm cabal.config ; fi
 - echo $PATH
 - OPTIMISATION=-O1 GHC_VERSION=${GHCVER} BUILD_TESTS=yes CORES=2 BIN_DIR=$(pwd)/bin make

 - ls -l $(find bin -type f)

script:
 - time dist/build/conjure-testing/conjure-testing -p basic/set01 +RTS -s
 - cabal sdist   # tests that a source-distribution can be generated

after_success:
 - make freeze
 - git diff cabal.config

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc
    - .cabal-sandbox
    - dist
    - bin

