version: 1.0.{build}

build_script:
- cmd: >-
    REM pick a stack file
    copy etc\hs-deps\stack-8.0.yaml stack.yaml

    REM getting stack
    curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
    7z x stack.zip stack.exe

    REM install GHC
    stack setup | FIND /V "Extracting  "

    REM this is make preinstall, translated to CMD
    bash etc\build\version.sh
    stack runhaskell etc\build\gen_Operator.hs
    stack runhaskell etc\build\gen_Expression.hs

    REM compile conjure
    stack build --test --no-run-tests

test_script:
- cmd: >-
    stack test --test-arguments "--hide-successes --select-tests=quick +RTS -s"
